version: "3.2"
services:
  gen-postgres:
    image: postgres
    container_name: gen-postgres
    restart: always
    ports:
      - "5234:5432"
    networks:
      - gen_dev_net      
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
    volumes:
      - ../volumes/postgres:/var/lib/postgresql/data
      
  gen-pgadmin:
    image: dpage/pgadmin4
    container_name: gen-pgadmin
    restart: always
    ports:
      - "8083:80"
    networks:
      - gen_dev_net      
    environment:
      PGADMIN_DEFAULT_EMAIL: pgadmin@gen-env.com
      PGADMIN_DEFAULT_PASSWORD: ${POSTGRES_PASSWORD}
    volumes:
      - ../volumes/pgadmin:/var/lib/pgadmin

networks:
  gen_dev_net:
    external: true
    driver: bridge      